### ISSUE TITLE
Coredump on Arch Linux with Mesa OpenCL driver

### ISSUE THREAD

**Issue by NeoChen1024** [xmrig/xmrig-amd#275]
Hardware:
AMD Ryzen 5 2400G (internal GPU)
MSI B350M motherboard

Package Version:
```
opencl-mesa 19.1.6-1
opencl-headers 2:2.2.20170516-2
ocl-icd 2.2.12-3
```
Backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007f8b1e0be0cd in clCreateCommandQueueWithProperties () from /usr/lib/libOpenCL.so
#2  0x0000562bb41e8133 in OclLib::createCommandQueue(_cl_context*, _cl_device_id*, int*) ()
#3  0x0000562bb41cd36c in InitOpenCLGpu(int, _cl_context*, GpuContext*, char const*, xmrig::Config*) ()
#4  0x0000562bb41d13c4 in InitOpenCL(std::vector<GpuContext*, std::allocator<GpuContext*> > const&, xmrig::Config*, _cl_context**) ()
#5  0x0000562bb421c92a in Workers::start(xmrig::Controller*) ()
#6  0x0000562bb41ee383 in xmrig::App::exec() ()
#7  0x0000562bb41c5b5f in main ()
```
Compiled binary and coredump attached
[xmrig-amd.core.gz](https://github.com/xmrig/xmrig-amd/files/3595924/xmrig-amd.core.gz)
[xmrig-amd.gz](https://github.com/xmrig/xmrig-amd/files/3595925/xmrig-amd.gz)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
